### PR TITLE
Add horizontal spacing to testDF data frame tables 

### PR DESCRIPTION
**Pull request by ViktorVerstraelen**
The tables produced by knitr::kable have no styling by default making them hard to read.
Added an HTML attribute to create spacing between the table columns.

### CODE REVIEW

**Comment by bmesuere** [comment]
@ViktorVerstraelen can you add a screenshot of the visual change?
On dodona, we have a table style that's used on almost all pages. You can use it by adding the class "table" to the table. Maybe that helps as well?

**Comment by ViktorVerstraelen** [comment]
I didn't know that, i will try that instead!

**Comment by ViktorVerstraelen** [comment]
@bmesuere I changed the padding to class = "table".  Here's an example of what the table looked like without any styling
table

**Comment by bmesuere** [comment]
Can you also add a screenshot of how it looks now? This way if we ever look back to this PR, we get a clearer idea of the changes.

**Comment by ViktorVerstraelen** [comment]
Is there a way for me to see how it will look in dodona? I can currently only test on the command line so i can only see the HTML code.

**Comment by bmesuere** [comment]
In this case, the easiest way is cheating a bit and use the browser dev tools to add the class to the table from the first screenshot.

**Comment by ViktorVerstraelen** [comment]
Hadn't thought of that!
table_new

**Review by bmesuere — APPROVED** [review]

**Pull request merged**
