### PR TITLE
code cleanup + small fixes

### PR DESCRIPTION
**Pull request by gubogaer**
bug fixed: error when student code defines function

addition: ast testing in contextWithImage is now possible

code cleanup and small indentation fixed

### CODE REVIEW

**Comment by charvp** [comment]
Can you rebase this on current master first? I changed the organization of the files a little this morning.

**Comment by gubogaer** [comment]
Ok and did you change the content of utils-ast.R or can I just overwrite it?

**Comment by charvp** [comment]
Except for making the whitespace consistent over the entire project I didn't make any changes.

**Comment by gubogaer** [comment]
Ok I've overwritten the file and made whitespace consistent again

**Review by charvp — APPROVED** [review]

**Pull request merged**
